export const PALAVRAS_RUINS = new Set([
    "adicional",
    "reduzido",
    "junto",
    "sem",
    "uma única",
    "através de",
    "adicional",
    "dos mesmos",
    "da mesma forma que",
    "porém",
    "era",
    "o indivíduo",
    "das mesmas",
    "possui",
    "dele",
    "dela",
    "existir",
    "no momento em que",
    "bastante",
    "encontra-se",
    "igualmente",
    "através do",
    "através da",
    "até mesmo",
    "isto",
    "a mulher",
    "no meio",
    "foi",
    "posteriormente",
    "falta de",
    "realmente",
    "aos mesmos",
    "possuir",
    "deles",
    "quem é",
    "nas mesmas",
    "esse mesmo",
    "os mesmos",
    "se encontram",
    "tu",
    "possui",
    "se foram",
    "essa mesma",
    "em um",
    "nem sequer",
    "deles",
    "meu próprio",
    "minha própria",
    "possuem",
    "em uma",
    "através dos",
    "as mulheres",
    "existia",
    "ser",
    "qualquer",
    "será que",
    "a gente",
    "possuímos",
    "a ele/ela",
    "deles próprios",
    "essas mesmas",
    "esses mesmos",
    "através das",
    "este mesmo",
    "se fosse",
    "dele próprio",
    "vós",
    "você",
    "a eles",
    "meus próprios",
    "minhas próprias",
    "teu próprio",
    "tua própria",
    "teus próprios",
    "tuas próprias",
    "nosso próprio",
    "nossa própria",
    "nossos próprios",
    "nossas próprias",
    "dela mesma",
    "delas mesmas",
    "esta mesma",
    "estes mesmos",
    "estas mesmas",
    "aquele mesmo",
    "aquela mesma",
    "aqueles mesmos",
    "aquelas mesmas",
    "isso mesmo",
    "aquilo mesmo",
    "encontro-me",
    "nos encontramos",
    "estive presente",
    "esteve presente",
    "estivemos presentes",
    "estiveram presentes",
    "estava presente",
    "estávamos presentes",
    "estavam presentes",
    "ou então",
    "no local onde",
    "isso",
    "ainda que",
    "não obstante",
    "pois",
    "enquanto isso",
    "entretanto",
    "todavia",
    "consequentemente",
    "além disso",
    "anteriormente",
    "contudo",
    "até mesmo",
    "à frente",
    "acerca de",
    "quanto a isso",
    "somente",
    "a partir de",
    "uma única vez",
    "de acordo com",
    "ao lado"
  ]);
  